name: IterationTimer
options:
  bundleIdPrefix: com.hal1437
  groupSortPosition: top
  deploymentTarget: 14.0
  developmentLanguage: ja
  xcodeVersion: "12.5"
  
settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
  config:
    debug:
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"

targets:
  IterationTimer:
    type: application
    platform: iOS
    sources: 
      - IterationTimer
      - path: IterationTimerWidget/IterationTimerWidget.intentdefinition
    settings:
      configs:
        debug:
          CUSTOM_BUILD_SETTING: my_debug_value
        release:
          CUSTOM_BUILD_SETTING: my_release_value
    scheme:
      testTargets:
        - IterationTimerTests
        - IterationTimerCoreTests
        - IterationTimerModelTests
        - IterationTimerUITests
      gatherCoverageData: true
    dependencies:
      - target: IterationTimerCore
      - target: IterationTimerModel
      - target: IterationTimerUI
      - target: IterationTimerWidget

  IterationTimerCore:
    platform: iOS
    type: framework
    sources: IterationTimerCore
    scheme:
      testTargets:
        - IterationTimerCoreTests
      gatherCoverageData: true

  IterationTimerModel:
    platform: iOS
    type: framework
    sources: IterationTimerModel
    scheme:
      testTargets:
        - IterationTimerModelTests
      gatherCoverageData: true
    dependencies:
      - target: IterationTimerCore

  IterationTimerUI:
    platform: iOS
    type: framework
    sources: IterationTimerUI
    scheme:
      testTargets:
        - IterationTimerUITests
      gatherCoverageData: true
    dependencies:
      - target: IterationTimerCore

  IterationTimerWidget:
    type: app-extension
    platform: iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hal1437.IterationTimer.IterationTimerWidget
        INFOPLIST_FILE: IterationTimerWidget/Info.plist
    sources:
      - IterationTimerWidget
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: WidgetKit.framework
      - target: IterationTimerCore
      - target: IterationTimerModel
      - target: IterationTimerUI

  IterationTimerTests:
    platform: iOS
    type: bundle.unit-test
    sources: Test/IterationTimerTests
    dependencies:
      - target: IterationTimer

  IterationTimerCoreTests:
    platform: iOS
    type: bundle.unit-test
    sources: Test/IterationTimerCoreTests
    dependencies:
      - target: IterationTimerCore

  IterationTimerModelTests:
    platform: iOS
    type: bundle.unit-test
    sources: Test/IterationTimerModelTests
    dependencies:
      - target: IterationTimerModel

  IterationTimerUITests:
    platform: iOS
    type: bundle.unit-test
    sources: Test/IterationTimerUITests
    dependencies:
      - target: IterationTimerUI

schemes:
  IterationTimerWidgetExtension: # Scheme名は任意のものを
    build:
      targets:
        IterationTimerWidget: all
        IterationTimer: all
    run:
      config: Debug
      askForAppToLaunch: true
      debugEnabled: false
      environmentVariables:
        - variable: _XCWidgetKind
          value:
          isEnabled: false
        - variable: _XCWidgetDefaultView
          value: timeline
          isEnabled: false
        - variable: _XCWidgetFamily
          value: medium
          isEnabled: false
    test:
      config: Debug
    profile:
      config: Release
      askForAppToLaunch: true
    analyze:
      config: Debug
    archive:
      config: Release
