name: IterationTimer
options:
  bundleIdPrefix: com.hal1437
  groupSortPosition: top
  deploymentTarget: 14.0
targets:
  IterationTimer:
    type: application
    platform: iOS
    sources: [IterationTimer]
    settings:
      configs:
        debug:
          CUSTOM_BUILD_SETTING: my_debug_value
        release:
          CUSTOM_BUILD_SETTING: my_release_value

  IterationTimerModel:
    platform: iOS
    type: framework
    sources: IterationTimerModel

  IterationTimerModelTests:
    platform: iOS
    type: bundle.unit-test
    sources: IterationTimerModelTests
    dependencies:
      - target: IterationTimerModel
