name: IterationTimer
options:
  bundleIdPrefix: com.hal1437
  groupSortPosition: top
targets:
  IterationTimer:
    type: application
    platform: iOS
    deploymentTarget: 13.0
    sources: [IterationTimer]
    settings:
      configs:
        debug:
          CUSTOM_BUILD_SETTING: my_debug_value
        release:
          CUSTOM_BUILD_SETTING: my_release_value
