name: IterationTimer
options:
  bundleIdPrefix: com.hal1437
  groupSortPosition: top
  deploymentTarget: 14.0
  developmentLanguage: ja
  xcodeVersion: "13.0"

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    majorVersion: 9.6.0

settings:
  base:
    MARKETING_VERSION: 1.1.1
    CURRENT_PROJECT_VERSION: 1
  config:
    debug:
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"

targets:
  IterationTimer:
    type: application
    platform: iOS
    sources: 
      - IterationTimer
    settings:
      base:
        INFOPLIST_PREPROCESS: true
      configs:
        debug:
          CODE_SIGN_IDENTITY: Apple Development
          CODE_SIGN_ENTITLEMENTS: IterationTimer/IterationTimer.entitlements
          PROVISIONING_PROFILE_SPECIFIER: com.hal1437.IterationTimer
          DEVELOPMENT_TEAM: JTT4T82QAY
        release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          CODE_SIGN_ENTITLEMENTS: IterationTimer/IterationTimer.entitlements
          PROVISIONING_PROFILE_SPECIFIER: match AppStore com.hal1437.IterationTimer
          DEVELOPMENT_TEAM: JTT4T82QAY
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: IterationTimerCore
      - target: IterationTimerModel
      - target: IterationTimerUI
      - target: IterationTimerWidget
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseCrashlytics
    entitlements:
      path: IterationTimer/IterationTimer.entitlements
      properties:
        com.apple.security.application-groups: [group.IterationTimer.timers]
        aps-environment: development
        com.apple.developer.ubiquity-kvstore-identifier: $(TeamIdentifierPrefix)$(CFBundleIdentifier)
    preBuildScripts:
      - name: Set app build version
        script: |
                buildNumber=$(git rev-list HEAD --count)
                /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $buildNumber" "${TEMP_DIR}/Preprocessed-Info.plist"
        basedOnDependencyAnalysis: false
    postbuildScripts:
      - name: Upload dSYM
        script: |
                if [ -f $(SRCROOT)/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run ]; then
                    "$(SRCROOT)/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
                elif [ -f ${BUILD_DIR%Build/*}SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run ]; then
                    "${BUILD_DIR%Build/*}SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
                else
                    echo "not found Crashlytics/run"
                fi
        inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
          - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)

  IterationTimerCore:
    platform: iOS
    type: framework
    sources: IterationTimerCore
    scheme:
      testTargets:
        - IterationTimerCoreTests
      gatherCoverageData: true

  IterationTimerModel:
    platform: iOS
    type: framework
    sources: IterationTimerModel
    scheme:
      testTargets:
        - IterationTimerModelTests
      gatherCoverageData: true
    dependencies:
      - target: IterationTimerCore

  IterationTimerUI:
    platform: iOS
    type: framework
    sources: IterationTimerUI
    scheme:
      testTargets:
        - IterationTimerUITests
      gatherCoverageData: true
    dependencies:
      - target: IterationTimerCore

  IterationTimerWidget:
    type: app-extension
    platform: iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hal1437.IterationTimer.IterationTimerWidget
        INFOPLIST_FILE: IterationTimerWidget/Info.plist
        INFOPLIST_PREPROCESS: true
      configs:
        debug:
          CODE_SIGN_IDENTITY: Apple Development
          PROVISIONING_PROFILE_SPECIFIER: com.hal1437.IterationTimer.IterationTimerWidget
          DEVELOPMENT_TEAM: JTT4T82QAY
        release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AppStore com.hal1437.IterationTimer.IterationTimerWidget
          DEVELOPMENT_TEAM: JTT4T82QAY
    sources:
      - IterationTimerWidget
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: WidgetKit.framework
      - target: IterationTimerCore
      - target: IterationTimerModel
      - target: IterationTimerUI
    entitlements:
      path: IterationTimerWidget/IterationTimerWidget.entitlements
      properties:
        com.apple.security.application-groups: [group.IterationTimer.timers]
        com.apple.developer.ubiquity-kvstore-identifier: $(TeamIdentifierPrefix)com.hal1437.IterationTimer
    preBuildScripts:
      - name: Set app build version
        script: |
                buildNumber=$(git rev-list HEAD --count)
                /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $buildNumber" "${TEMP_DIR}/Preprocessed-Info.plist"
        basedOnDependencyAnalysis: false

  IterationTimerTests:
    platform: iOS
    type: bundle.unit-test
    sources: Test/IterationTimerTests
    dependencies:
      - target: IterationTimer
    settings:
      TEST_HOST: ""

  IterationTimerCoreTests:
    platform: iOS
    type: bundle.unit-test
    sources: Test/IterationTimerCoreTests
    dependencies:
      - target: IterationTimerCore

  IterationTimerModelTests:
    platform: iOS
    type: bundle.unit-test
    sources: Test/IterationTimerModelTests
    dependencies:
      - target: IterationTimerModel

  IterationTimerUITests:
    platform: iOS
    type: bundle.unit-test
    sources: Test/IterationTimerUITests
    dependencies:
      - target: IterationTimerUI

schemes:
  IterationTimer: 
    build:
      targets:
        IterationTimerWidget: all
        IterationTimer: all
    run: 
      commandLineArguments: 
        "-FIRDebugEnabled": true
    test:
      gatherCoverageData: true
      coverageTargets:
        - IterationTimer
        - IterationTimerCore
        - IterationTimerModel
        - IterationTimerUI
      targets:
        - IterationTimerTests
        - IterationTimerCoreTests
        - IterationTimerModelTests
        - IterationTimerUITests
  IterationTimerWidgetExtension:
    build:
      targets:
        IterationTimerWidget: all
        IterationTimer: all
    run:
      config: Debug
      askForAppToLaunch: true
      debugEnabled: false
      environmentVariables:
        - variable: _XCWidgetKind
          value:
          isEnabled: false
        - variable: _XCWidgetDefaultView
          value: timeline
          isEnabled: false
        - variable: _XCWidgetFamily
          value: medium
          isEnabled: false
