name: IterationTimer
options:
  bundleIdPrefix: com.hal1437
  groupSortPosition: top
  deploymentTarget: 14.0
  developmentLanguage: ja
  xcodeVersion: "12.5"
  
settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
  config:
    debug:
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"

targets:
  IterationTimer:
    type: application
    platform: iOS
    sources: [IterationTimer]
    settings:
      configs:
        debug:
          CUSTOM_BUILD_SETTING: my_debug_value
        release:
          CUSTOM_BUILD_SETTING: my_release_value
    scheme:
      testTargets:
        - IterationTimerTests
        - IterationTimerCoreTests
        - IterationTimerModelTests
        - IterationTimerUITests
      gatherCoverageData: true
    dependencies:
      - target: IterationTimerModel
      - target: IterationTimerUI

  IterationTimerCore:
    platform: iOS
    type: framework
    sources: IterationTimerCore
    scheme:
      testTargets:
        - IterationTimerCoreTests
      gatherCoverageData: true

  IterationTimerModel:
    platform: iOS
    type: framework
    sources: IterationTimerModel
    scheme:
      testTargets:
        - IterationTimerModelTests
      gatherCoverageData: true
    dependencies:
      - target: IterationTimerCore

  IterationTimerUI:
    platform: iOS
    type: framework
    sources: IterationTimerUI
    scheme:
      testTargets:
        - IterationTimerUITests
      gatherCoverageData: true
    dependencies:
      - target: IterationTimerCore

  IterationTimerTests:
    platform: iOS
    type: bundle.unit-test
    sources: Test/IterationTimerTests
    dependencies:
      - target: IterationTimer

  IterationTimerCoreTests:
    platform: iOS
    type: bundle.unit-test
    sources: Test/IterationTimerCoreTests
    dependencies:
      - target: IterationTimerCore

  IterationTimerModelTests:
    platform: iOS
    type: bundle.unit-test
    sources: Test/IterationTimerModelTests
    dependencies:
      - target: IterationTimerModel

  IterationTimerUITests:
    platform: iOS
    type: bundle.unit-test
    sources: Test/IterationTimerUITests
    dependencies:
      - target: IterationTimerUI
