# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :build do
    Dir.chdir("../") do
      sh("xcodebuild", "-resolvePackageDependencies")
    end

    gym(
      scheme: "IterationTimer"
    )
  end

  lane :test do
    Dir.chdir("../") do
      sh("xcodebuild", "-resolvePackageDependencies")
    end

    scan(
      project: "IterationTimer.xcodeproj",
      scheme: "IterationTimer"
    )
  end

  lane :build_for_appstore do
    build_app(
      scheme: "IterationTimer",
      export_method: "app-store",
    )
  end

  lane :upload_app do
    pilot(
      username: "halstroemeria@gmail.com",
      ipa: "./IterationTimer.ipa",
    )
  end
  
  lane :deliver_app do
    deliver(
      build_number: sh("git rev-list HEAD | wc -l | tr -d ' '"),
      username: "halstroemeria@gmail.com",
      overwrite_screenshots: true,
      submit_for_review: false,
      skip_binary_upload: true,
      force: true,
    )
  end
end
