# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :build do
    Dir.chdir("../") do
      sh("xcodebuild", "-resolvePackageDependencies")
    end

    gym(
      scheme: "IterationTimer"
    )
  end

  lane :test do
    Dir.chdir("../") do
      sh("xcodebuild", "-resolvePackageDependencies")
    end

    scan(
      project: "IterationTimer.xcodeproj",
      scheme: "IterationTimer"
    )
  end

  lane :match_appstore do
    setup_ci(
      force: true,
      provider: "travis",
    )

    username = ENV['USERNAME']
    personal_github_access_token = ENV["PERSONAL_GITHUB_ACCESS_TOKEN"]
    authorization_token_str = "#{username}:#{personal_github_access_token}"
    git_basic_authorization = Base64.strict_encode64(authorization_token_str)

    match(
      type: "appstore",
      git_url: "git@github.com:hal1437/IterationTimer_Match.git",
      app_identifier: ["com.hal1437.IterationTimer", "com.hal1437.IterationTimer.IterationTimerWidget"],
      git_basic_authorization: git_basic_authorization,
      username: "halstroemeria@gmail.com",
      readonly: true,
    )
  end

  lane :build_for_appstore do
    build_app(
      scheme: "IterationTimer",
      export_method: "app-store",
    )
  end

  lane :upload_app do
    api_key = app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_content: ENV['ASC_KEY_CONTENT'],
    )

    pilot(
      api_key: api_key,
      ipa: "./IterationTimer.ipa",
    )
  end
  
  lane :deliver_app do
    api_key = app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_content: ENV['ASC_KEY_CONTENT'],
    )

    deliver(
      build_number: sh("git rev-list HEAD | wc -l | tr -d ' '"),
      api_key: api_key,
      overwrite_screenshots: true,
      submit_for_review: false,
      skip_binary_upload: true,
      force: true,
    )
  end
end
